# Generated by Django 6.0.1 on 2026-01-15 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_final_cards', models.JSONField(default=list)),
                ('dealer_final_cards', models.JSONField(default=list)),
                ('player_final_score', models.IntegerField()),
                ('dealer_final_score', models.IntegerField()),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('push', 'Push'), ('blackjack', 'Blackjack')], max_length=20)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Game histories',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_cards', models.JSONField(default=list)),
                ('dealer_cards', models.JSONField(default=list)),
                ('player_score', models.IntegerField(default=0)),
                ('dealer_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('player_win', 'Player Win'), ('dealer_win', 'Dealer Win'), ('push', 'Push'), ('blackjack', 'Blackjack'), ('player_bust', 'Player Bust'), ('dealer_bust', 'Dealer Bust')], default='in_progress', max_length=20)),
                ('is_player_turn', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
